### PR TITLE
[TECH SUPPORT] LPS-69369 Setting virtual host for private page breaks site control p…

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this fix.
For more information about the issue see:
https://issues.liferay.com/browse/LPS-69369
Or the previous review:
jonathanmccann#1148

Regards,

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Rimi,

Please, rebase your branch to latest master and push to your origin with ```---force```, then hit ci retest.

Thanks!

@rimisaadouwork

**Comment by lipusz** [comment]
ci:stop

**Comment by rimisaadouwork** [comment]
The fix is not needed any more because it's already fixed on master.

**Comment by lipusz** [comment]
Then, please update/close https://issues.liferay.com/browse/LPS-69369 accordingly. Thanks! @rimisaadouwork

**Pull request closed without merging**
