### PR TITLE
LPS-71933

### PR DESCRIPTION
**Pull request by holatuwol**
Ray, you're the only one from engineering whose name appears on the file, so I think you're the best person to review this. If I'm mistaken, let me know and I can route this through someone else.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:reopen

I believe the issue has been resolved here, but I can't tell from the messages whether the overrides are CAUSING the problem or SOLVING the problem:

https://github.com/liferay/liferay-portal/commit/079c994260a6bfcad53a75eb90a674c84ef6f142
https://github.com/liferay/liferay-portal/blob/master/modules/apps/web-experience/journal/journal-content-web/bnd.bnd

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

I believe this error was fixed by https://github.com/liferay/liferay-portal/commit/d913165fca7b5a2b76f0e2f5a94290c4ba8803e3#diff-e9a5d3603f55b21679620a9f8d3371ee

**Comment by holatuwol** [comment]
ci:retest

Looking at the [testray report](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=66672399), I don't see any reason why my change would make JBoss timeout when attempting to startup (which is what causes the failure), so I'm going to assume there was a network hiccup.

**Comment by holatuwol** [comment]
ci:retest

Most likely fixed by this series of commits.

https://github.com/liferay/liferay-portal/commit/8e1664b36cfcbd66054adc45df822ca8ba3ea175#diff-ad2c7d9d507c1c013f8345d1e04cb2dd
https://github.com/liferay/liferay-portal/commit/9ff653aaea115a88421c374222ce6102aaf12c37#diff-ad2c7d9d507c1c013f8345d1e04cb2dd

**Comment by holatuwol** [comment]
Known issue: pull request tester isn't automatically responding to ci:retest right now.

https://loop.liferay.com/home/-/loop/feed/4963513

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

Looking at the [testray report](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=66896400), the tests that are failing have a history of random failures, and none of them are in any way tied to user update.

**Comment by holatuwol** [comment]
@rotty3000, do you know when you'll have time to look at this pull request, or if I should send it to a different reviewer?

**Comment by rotty3000** [comment]
I'm ok with this change. But I'm travelling and won't be back till Monday. Perhaps @shuyangzhou would be willing to review?

**Comment by shuyangzhou** [comment]
@holatuwol feel free to send it over to me.

**Comment by holatuwol** [comment]
@rotty3000, I'm okay with waiting until Monday. If you find yourself clobbered with work when you're done traveling, I'll resend to @shuyangzhou at that time. Thanks!

**Comment by holatuwol** [comment]
Sent https://github.com/shuyangzhou/liferay-portal/pull/4206, will close if the other pull request closes first.

**Pull request closed without merging**
