### PR TITLE
LPS-55355 As a developer I would like to extract Shopping portlet

### PR DESCRIPTION
**Pull request by peterfellwock**
This one is complete.

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28365. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/d794d6a~4...d794d6a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
