### PR TITLE
LPS-62777 Close registry trackers

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by rotty3000** [comment]
nice!

**Comment by rotty3000** [comment]
nice!

**Comment by csierra** [comment]
:+1:

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35414. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
