### PR TITLE
Lps 59517 8

### PR DESCRIPTION
**Pull request by amosfong**
does this look ok?

### CODE REVIEW

**Comment by amosfong** [comment]
-The verifier will throw the exception which will cause the failed resolve. I can give a better error message in the exception this way.

-I pass the bundle to the verifier because I think I need the bundleId to register a servletfilter for developer licenses. And I'll need to create some sort of bundleEventListener to remove the filter as well. I don't know if I'll need something more in the future so I'm just passing in the entire bundle object.

**Comment by rotty3000** [comment]
What's the servlet filter for??? I don't get that at all!

**Comment by amosfong** [comment]
Yea it's kind of weird...for plugins with a developer license they decided
if you go over the session limit we restrict access to control panel.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32643. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/a450cda~3...a450cda) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
