### PR TITLE
petra-concurrent

### PR DESCRIPTION
**Pull request by jrao**
Add petra-concurrent

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
@jrao can you rebase this and push it up so it rebuilds (no need to close this PR).

I think there were upstream issues.

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
Hey @jrao for some reason this branch doesn't work anymore. Can you resend the PR?

**Comment by jrao** [comment]
@rotty3000 Sent https://github.com/rotty3000/liferay-portal/pull/1355

**Pull request closed without merging**
