### PR TITLE
Add petra-concurrent

### PR DESCRIPTION
**Pull request by jrao**
Add petra-concurrent module

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51478. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
