### PR TITLE
LPS-63144 Increase size for Configuration pid to 511 bytes

### PR DESCRIPTION
**Pull request by topolik**
https://issues.liferay.com/browse/LPS-63144

/cc @JorgeFerrer

### CODE REVIEW

**Comment by topolik** [comment]
There are real test errors, need to look what's wrong.

**Comment by rotty3000** [comment]
Seems like the column length was still too long?

**Comment by topolik** [comment]
Yes, the problem is the 767 bytes limit for UNIQUE constraint in InnoDB.

We have VARCHAR primary key, the default UTF-8 in MySQL is using 3 bytes per char => 767 / 3 == 255 VARCHARs ... we already reached the limit

This also means we don't support full UTF-8 (utf8mb4 encoding) where the max is 767/4 == VARCHAR(191).

Want we change that?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Hi @topolik not sure what to do with this! Do we really need to increase the size? Can you give me an example of a failing case?

**Comment by topolik** [comment]
Hi Ray,

the failing case is when you create a configuration with long enough pid.
Luckily we don't have such any today.

I'd close it as won't fix - a limitation of current design. We would need
to introduce a different primary key and implement UNIQUE check outside DB.

-- tom +

**Comment by topolik** [comment]
Closed the ticket as won't fix. Thanks!

**Pull request closed without merging**
