### PR TITLE
LPS-67378 rebased

### PR DESCRIPTION
**Pull request by juangon**
Hi @rotty3000. This is needed to fix a test from Bridge TCK. Those attributes should be obtained from the request from first servlet in chain.

Thanks!

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
@rotty3000 I don't like those last failing tests (AccesToPathXXX). But I checked this some days ago and they weren't failing: https://github.com/juangon/liferay-portal/pull/40.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1241. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
