### PR TITLE
LPS-56274

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Seems like these errors are happening across the board. Let me know though.

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27497. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
