### PR TITLE
[TS] LPS-78313

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test

**Comment by yuhai** [comment]
Hi @rotty3000

Hope you are well.

Since the issue came from EE customer, could you please review this when you have free time?

Regards,
Hai

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55853. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
