### PR TITLE
LPS-57826 Permissions and Staging

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

/cc @matethurzo

here is an update of https://github.com/rotty3000/liferay-portal/pull/1033, therefore many of the commits can be squashed together, but I kept them for now for clarity.

Please let me know if you think this way - fix it on framework/services level - is correct. 

When I tested it my breakpoints in staging->live groupId rewriting logic were hit frequently when manipulating with portlets and site assignments in staging. So another option would be to identify all places where we send the wrong groupId into services and rewrite the API consumer parts. But this won't fix future uses of the API where developers (not aware of staging) may call services with the wrong groupId again.

PR message from the last time:
----
I tried to fix the staging permissions checking in portal framework:
1, checking permissions always on live groupId ... wrapper around PermissionChecker
... to remove staging logic from AdvancedPermissionChecker into own class
... to support user-defined permission checkers so that they will work with staging transparently
2, site-related membership is done on live groupId (user->site, userGroup->site, Org->Site)
... Advices around GroupLS and related LocalServices that are in 1:N relation
... Advices for M:N relations where group is present (User-Group-Role + UserGroup-Group-Role)

I tried to fix the teams but they are fundamentally broken: https://issues.liferay.com/browse/LPS-59563

So teams are in unstable state right now when staging is enabled.

/cc @matethurzo

EDIT: in case we decide to fix LPS-59563 as proposed in the ticket, I have prepared (untested) solution to check staging team permissions in staging and live team permissions in live (https://github.com/topolik/liferay-portal/commits/LPS-57826-III)

New Strict type checking
----
On top of this I changed advices implementation to use `Method` caches instead of relying on method names, in case we add/remove parameter or overload a method.

When developers introduce a new API that is related to Group, I added a simple coverage check so that they won't forget to decide whether the method is staging related (has groupId as a parameter).

Please let me know if you want to discuss it on call. Thank you!

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by stian-sigvartsen** [comment]
LPS-59736 might need to be addressed together with this PR.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31377. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32666. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
