### PR TITLE
LPS 60542 Cleaning up background task leftovers

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Can you rebase please? I got rebase errors. Thx! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by peterfellwock** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33244. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/57dde7f~1...57dde7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
