### PR TITLE
LPS-70547 Allow httpclient-osgi v4 to be used in modules

### PR DESCRIPTION
**Pull request by jrao**
LPS-70547 Allow httpclient-osgi v4 to be used in modules

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
ci:retest

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
ci:stop

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1392. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/7135212e4fe3~3...7135212e4fe3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
