### PR TITLE
LPS-178621 macosx fix

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi Ray, I had to remove lastModified timestamp check to make tests pass in MacOSx.
(we will see CI) here CI fails without fix:
https://github.com/liferay-headless/liferay-portal/pull/1097

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
Hi @rotty3000 this PR is without changes and it doesn't pass CI:
https://github.com/liferay-headless/liferay-portal/pull/1097

**Comment by rotty3000** [comment]
Hi @igorbeslic I'm testing a cross platform fix for the test here https://github.com/rotty3000/liferay-portal/pull/1495

**Comment by rotty3000** [comment]
@igorbeslic you can continue your work, I will forward the test fix to bchan.

**Pull request closed without merging**
