### PR TITLE
[TECHNICAL SUPPORT] LPS-64698 Fix DeepNamedValueScanner related performance issue

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi @rotty3000,

Based on your request on https://github.com/igorspasic/liferay-portal/pull/94#issuecomment-210121392 I send this PR to you.

Regards,
Vilmos

### CODE REVIEW

**Comment by vilmospapp** [comment]
ci:retest

**Comment by vilmospapp** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39740. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/4c6ae44~1...4c6ae44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
