### PR TITLE
Add support to start bundles which the spring files defined in "spring.infrastructure.configs" depend on.

### PR DESCRIPTION
**Pull request by tinatian**
@mhan810 @shuyangzhou

Hi Ray,

I met a problem about the order of starting osgi bundles while trying to extract ehcache as a bundle. 

The problem is some bundles need to be started, or in other words, some services need to be registered, before the spring files setting in "spring.infrastructure.configs" are parsed, since some spring beans defined in those files depend on the bundle services.

In this pull request, I modified the order we start bundles, but I am not sure if it is safe to do this or if you are OK with this solution.  Could you please take a look at it? 

This pull request is only a rough version to confirm with you if those changes are OK, I will send you a formal one later.

And I also tried to initialize spring files in "spring.infrastructure.configs" after osgi framework is started, some exceptions came up, I think you should have a good reason to initialize those before framework is started, right?

Thanks.
Tina.

### CODE REVIEW

**Comment by rotty3000** [comment]
Bundles should not have dependency on start order. but I'll take a look to see what can be done.

The whole goal of breaking the spring context into two pieces `spring.infrastructure.configs` vs 'spring.configs` was to allow some beans which would not depend on osgi to be created before the osgi runtime is initialized.

If there are beans in `spring.infrastructure.configs` which need services, then perhaps we should move those to `spring.configs`.

**Comment by tinatian** [comment]
So you mean it is safe to initialize all spring files after osgi framework is started? I remembered I met some exceptions when I tried this, I will try it on later one more time.

Another problem is bundles are stared asynchronously by fleix after framework is started. How do I make sure that a service has been registered before spring bean which depends on it is initialized?

Tina.

**Comment by rotty3000** [comment]
In core, you make an async dependency on a service by using a service tracker which will act like a callback to execute the logic only when the service becomes available.

We have many such examples already in the core.

**Comment by tinatian** [comment]
I know the service tractor we are using. Service tracker is a call back and we need to put the logic depends on the service we are watching in the call back method.

My problem here is I can not put the logic depends on services in call back method, so I need to make sure services are ready before spring bean is initialized.

Specifially, the problem here is in SingletonLiferayEhcacheRegionFactory which is initialized by hibernate. I wan to make "_liferayEhcacheRegionFactory" a service since we want to extract code related to ehcache. "_liferayEhcacheRegionFactory" would be used by hibernate when initializing spring beans, since service is registered async, service might not be intialized when spring bean is invoking "_liferayEhcacheRegionFactory", NPE comes up.

Tina.

**Comment by rotty3000** [comment]
I get it! However, since the portal is a separate thread from the initialization of the framework, the only thing you can do to ensure it can get a service is to wait for the service.

You can use `_serviceTracker.waitForService(timeout)`.

**Comment by rotty3000** [comment]
The better ways is to re-organize the logic to be a non-busy wait.

**Comment by rotty3000** [comment]
.. but I will look at this on Monday.

**Comment by tinatian** [comment]
I know I can do waiting, but it is fragile, I am seeking for a more robost solution since hibernate is one of the critical modules we need.

Any questions about these changes, please let me know.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi Ray,

I just found a bug in this solution, so I am going to close this pull request. Sorry to bother you too much.

I will try the wait method and see if my problem can be sloved elegantly. 

Thanks for all the help.
Tina.

Tina.

**Pull request closed without merging**
