### PR TITLE
LPS-44962

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
Ray, can you take a quick look. 

I did have 1 question: enums in Meta.  If you look @ TokenBasedConfiguration.logoutProcessorType and TokenBasedConfiguration.tokenLocation. These are really enum values from LogoutProcessorType and TokenLocation.  Is there a way to just express as the enum class?

**Comment by mhan810** [comment]
Btw, I added what I believe is the correct way in the last commit

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/mhan810/liferay-portal/pull/293. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
