### PR TITLE
LPS-64092

### PR DESCRIPTION
**Pull request by juangon**
Hi @rotty3000, finally here it is the Servlet API implementation. With these changes now we are using servlet API for adding servlets, listeners and filters and then registered in http whiteboard as always.

Just a few notes I've seen when changing this:
* Finally I had to create a ServletContextWrapper, as I needed some API to use in WabBundleProcessor that isn't available in ServletContext API.
* I had  to move the ServletContextWrapper and the two RegistrationImpls to servlet-context-helper module, as we need the wrapper there so JSP TLD listeners are added using the Servlet 3 API using our implementation (so its registered later using our execution flow).
* I've seen some things not being used, like filterDefinition.priority. When registering the filter in whiteboard I've set the SERVICE_RANKING to "0", which was the actual value set until now AFAIK.
* I've removed HTTP_WHITEBOARD_SERVLET_ERROR_PAGE as we weren't populating that, and I think there is no direct relation from the web.xml <servlet> or <servlet-mapping> that can be used. Anyway, as it was empty before, we aren't changing nothing actually.

If you have any question, please feel free to ask as always.

Thanks!

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37639. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/43de225~2...43de225) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37641. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/7286166~2...7286166) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37644. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/f3033eb~3...f3033eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37657. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/42b0ea1~4...42b0ea1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
