### PR TITLE
LPS-68984

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by hhuijser** [comment]
ci:retest

**Comment by hhuijser** [comment]
@rotty3000, can you have a look at this one, please?

**Comment by zxdgoal** [comment]
Hey Hugo 

Could we send it to someone else to review this pr?

Thanks
John.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/topolik/liferay-portal/pull/395. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
