### PR TITLE
LPS-64878

### PR DESCRIPTION
**Pull request by juangon**
Hi @rotty3000. The problem is all war files are being processed by Liferay. What we want (at least for JSF) is keep the WAB as is, so Liferay doesn't add unwanted files (liferay-portlet.xml, util-java etc), and doesn't change anything within the WAB (MANIFEST, web.xml ,etc).

I checked and it fixes the problem. Hope it makes sense.

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I don't think this is what we want... We're already check if a WAR has OSGi metadata in the WAB-converter. Can you explain why this additional code is needed? If we reach here for already calculated WABs then there is a bug much earlier.

**Comment by juangon** [comment]
@rotty3000 as per my tests, as this file is a WAR file, it falls under other deployer (don't remember if Portlet or Web) , which causes to be processed and messed up.

There are checks for module deployer that is should be a ".jar" file only. As this is a .war, it falls down under other deployer.

**Comment by rotty3000** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/38672 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
