### PR TITLE
LPS-54558 We are using File.mkdirs() method without checking its return value

### PR DESCRIPTION
**Pull request by laszlocsontos**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by rotty3000** [comment]
These look like legitimate failures. Can you check?

**Comment by jorgediaz-lr** [comment]
Hi all,

MockFile is a new class created a few days ago at LPS-54752   https://github.com/JorgeFerrer/liferay-portal/pull/509

@laszlocsontos can you add mkdirs(File file) at MockFile and resend your pull?

```java
@Override
public void mkdirs(File file) throws IOException {
}
````

Thank you

**Comment by rotty3000** [comment]
Closing for now but please re-open ore resend once an update is available. Thx! :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by laszlocsontos** [comment]
Hi Guys,

New PR: https://github.com/rotty3000/liferay-portal/pull/836

Cheers,
László

**Pull request closed without merging**
