### PR TITLE
[TS] LPS-76603

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
@rotty3000 
Did you have a chance to review this pull request?

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
@rotty3000 
Do we have a chance to review this pull request yet?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53992. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
