### PR TITLE
LPS-64837 70x

### PR DESCRIPTION
**Pull request by holatuwol**
Separate issue from what we've been discussing, but we were able to get this one working just fine by updating .bnd.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Wouldn't it be better to publish this library in the WAR? This way we can change it out to a new version if required? We're trying minimize the footprint of published APIs from the core.

**Comment by holatuwol** [comment]
Got it. @jonathanmccann, let's go with the previous plan and update the ivy.xml with the dependencies.

**Pull request closed without merging**
