### PR TITLE
LPS-68989 improvements

### PR DESCRIPTION
**Pull request by juangon**
Hi @rotty3000, after making previous changes for LPS-68989 @csierra and I had been talking about this change, so BundleUtil method does what is supposed to do only (as its method name states). Same logic than before anyway.

Additionally, I've added recommendations from https://github.com/brianchandotcom/liferay-portal/pull/44499#issuecomment-258478340 so errors are logged.

### CODE REVIEW

**Comment by juangon** [comment]
ci:reopen

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
Source formatter error hasn't to do with my changes :-(

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44967. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
