### PR TITLE
LPS-59983

### PR DESCRIPTION
**Pull request by holatuwol**
Fix typo in the name of the ReloadablePersistenceManager interface.

https://issues.liferay.com/browse/LPS-59983

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31932. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
