### PR TITLE
[TECHNICAL-SUPPORT] LPS-78199

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55851. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/2a694bc67e9f~1...2a694bc67e9f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
