### PR TITLE
LPS-54505 - Extract CSS from portal-web into front-end module

### PR DESCRIPTION
**Pull request by peterfellwock**
@mjbradford89 good job!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
@peterfellwock Hmm it looks like this latest failure might be because a test case is looking for the themes in a place where they no longer are, since they're in a bundle now.  I think we will have to change that test some how.

**Comment by mjbradford89** [comment]
actually it's not a test, it's the compile theme task trying to build themes who's parent is now in a bundle.  I will have to think about this one.

**Comment by rotty3000** [comment]
Shall I hold off on this until the issue is resolved?

**Comment by mjbradford89** [comment]
@rotty3000 Yes please hold off. We should be able to send you an updated pull today for this and for the necessary changes in liferay-plugins.

**Comment by peterfellwock** [comment]
@rotty3000 & @mjbradford89 please review in connection with https://github.com/rotty3000/liferay-plugins/pull/55 . We followed the following steps to get jenkins to use updated pull request: https://in.liferay.com/web/global.engineering/blog/-/blogs/new-tests-for-the-pull-request-tester-

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
This will fail as well. Closing and re-starting process.

**Pull request closed without merging**
