### PR TITLE
LPS-53865

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @holatuwol

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by holatuwol** [comment]
Looks like the build isn't properly recreating the "classes" folder in document-selector-web.

ci:retest

**Comment by holatuwol** [comment]
Checkout pull request:
```
[11:42] git fetch git@github.com:rotty3000/liferay-portal.git --no-tags pull/726/head:test
From github.com:rotty3000/liferay-portal
 * [new ref]         refs/pull/726/head -> test
[11:43] git checkout test
Switched to branch 'test'
```

Test compile of module that is failing to compile:
```
[11:43] cd modules/apps/document-selector/document-selector-web/
[11:44] ant clean jar
JAVA_HOME=/usr/lib/jvm/jdk1.7.0_65
Buildfile: /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/build.xml

clean:
   [delete] Deleting directory /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/classes
   [delete] Deleting: /home/minhchau/Work/liferay/trunk/portal-ce/tools/sdk/dist/com.liferay.document.selector.web-1.0.0.jar
   [delete] Deleting: /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/ivy.xml.MD5
   [delete] Deleting directory /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/lib

jar:
[ivy:resolve] :: Apache Ivy 2.3.0 - 20130110142753 :: http://ant.apache.org/ivy/ ::
[ivy:resolve] :: loading settings :: file = /home/minhchau/.m2/ivy-settings.xml
[ivy:retrieve] :: retrieving :: com.liferay#com.liferay.document.selector.web
[ivy:retrieve] 	confs: [default, internal]
[ivy:retrieve] 	1 artifacts copied, 0 already retrieved (753kB/6ms)
[ivy:retrieve] :: retrieving :: com.liferay#com.liferay.document.selector.web
[ivy:retrieve] 	confs: [default, internal]
[ivy:retrieve] 	0 artifacts copied, 0 already retrieved (0kB/3ms)
    [mkdir] Created dir: /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/classes
     [copy] Copying 9 files to /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/classes
     [copy] Copied 11 empty directories to 9 empty directories under /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/classes
    [javac] Compiling 4 source files to /home/minhchau/Work/liferay/trunk/portal-ce/modules/apps/document-selector/document-selector-web/classes
      [bnd] # com.liferay.document.selector.web (com.liferay.document.selector.web-1.0.0.jar) 16 

BUILD SUCCESSFUL
Total time: 7 seconds
```

**Comment by rotty3000** [comment]
it's actually because it needs to run git clean -fdx

that module got restructured and there's a docroot dir left behind.

**Comment by holatuwol** [comment]
Note that local builds create a "classes" folder while the CI server builds create a "docroot/WEB-INF/classes" folder for this module. No idea why.

**Comment by holatuwol** [comment]
Does this mean we should use the "wipe out current workspace" link and retest?

**Comment by rotty3000** [comment]
Probably would be the best!

On Tue, Mar 3, 2015 at 3:17 PM, Minhchau Dang <notifications@github.com>
wrote:

> Does this mean we should use the "wipe out current workspace" link and
> retest?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/liferay-portal/pull/726#issuecomment-77025685>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ServiceTestUtil.initServices() is failing now, so Jenkins status is yellow instead of red. I'm pretty sure I didn't touch any of the service initialization code, so I don't think the problem is caused by the commits on this ticket:

http://ci.liferay.org.es/jenkins//job/rotty3000/324/

**Comment by rotty3000** [comment]
Note the .es CI is currently not identical to the main CI in the US and so
I think you can ignore a lot of the error reporting that is happening with
it.

On Wed, Mar 4, 2015 at 2:47 PM, Minhchau Dang <notifications@github.com>
wrote:

> ServiceTestUtil.initServices() is failing now, so Jenkins status is yellow
> instead of red. I'm pretty sure I didn't touch any of the service
> initialization code, so I don't think the problem is caused by the commits
> on this ticket:
>
> http://ci.liferay.org.es/jenkins//job/rotty3000/324/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/liferay-portal/pull/726#issuecomment-77231824>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/holatuwol/liferay-portal/pull/45. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
