### PR TITLE
LPS-57826 Permissions and Staging

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

I tried to fix the staging permissions checking in portal framework:
1, checking permissions always on live groupId ... wrapper around PermissionChecker
... to remove staging logic from AdvancedPermissionChecker into own class
... to support user-defined permission checkers so that they will work with staging transparently
2, site-related membership is done on live groupId (user->site, userGroup->site, Org->Site)
... Advices around GroupLS and related LocalServices that are in 1:N relation
... Advices for M:N relations where group is present (User-Group-Role + UserGroup-Group-Role)

I tried to fix the teams but they are fundamentally broken: https://issues.liferay.com/browse/LPS-59563

So teams are in unstable state right now when staging is enabled.

/cc @matethurzo

EDIT: in case we decide to fix LPS-59563 as proposed in the ticket, I have prepared (untested) solution to check staging team permissions in staging and live team permissions in live (https://github.com/topolik/liferay-portal/commits/LPS-57826-III)

### CODE REVIEW

**Comment by matethurzo** [comment]
Hey @topolik,

This looks good from my perspective. I specifically like that the staging specific parts are being moved to the relevant code components.

**Comment by topolik** [comment]
rebased on master

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
Closing, real test failure. Will need more robust solution for advices to detect when contract broke - developers changed API.

**Comment by topolik** [comment]
Please see https://github.com/rotty3000/liferay-portal/pull/1037. Thank you

**Pull request closed without merging**
