### PR TITLE
LPS-53914 Remove unnecessary property since these portlets don't use struts

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Ray,

You only need to review this last commit: https://github.com/sergiogonzalez/liferay-portal/commit/93fd1ee0b18f2275a18bf8d199c1fcbe017348ce

The last should rebase properly.

Thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
'struts-path' is used for more than just struts, sadly. It's used for checking the validity of operations against portlets. @topolik, could you comment on this\? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
I believe this should be OK.

Having a portlet on a page, the struts-path check is used to avoid executing any struts action as it would belong to the portlet. By removing the struts-path it should not open any vulnerability.

And then it's used in p_p_auth/p_auth whitelists - it's possible to whitelist specific struts action.

@rotty3000 Did you mean anything else?

Thank you.

**Comment by rotty3000** [comment]
No, I just wanted you to make a sanity check!

Thx @topolik :)

Carrying on...

On Thu, Mar 5, 2015 at 8:49 AM, Tomáš Polešovský <notifications@github.com>
wrote:

> I believe this should be OK.
>
> Having a portlet on a page, the struts-path check is used to avoid
> executing any struts action as it would belong to the portlet. By removing
> the struts-path it should not open any vulnerability.
>
> And then it's used in p_p_auth/p_auth whitelists - it's possible to
> whitelist specific struts action.
>
> @rotty3000 <https://github.com/rotty3000> Did you mean anything else?
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/liferay-portal/pull/724#issuecomment-77366052>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24539. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Thanks guys!

**Pull request closed without merging**
