### PR TITLE
Lps 59517 3

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
Hey Ray,

This is the AppRegistryUtil check that will be called by your class whenever an OSGi module is deployed.

Also I'm not sure if I'm supposed to commit the rebuilt system.mf file, you can remove it if not.

Thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
this doesn't rebase cleanly on HEAD of master. please rebase.

**Comment by rotty3000** [comment]
@amosfong what did you want me to do with this?

**Comment by rotty3000** [comment]
Sorry, I see you resent this as #1045

**Pull request closed without merging**
