### PR TITLE
LPS-54489 - Extract WYSIWYG editors into a module

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
@rotty3000 @mjbradford89 fixing....

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by peterfellwock** [comment]
Closing, @mjbradford89 merged in other changes.

**Pull request closed without merging**
