### PR TITLE
LPS-55355 As a developer I would like to extract Shopping portlet (With new Build Service structure)

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/957. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28820. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/cb62a4f~5...cb62a4f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29038. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/62451e3~14...62451e3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29039. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/2f668a1~14...2f668a1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29090. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/3326453~17...3326453) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
