### PR TITLE
LPS-69889

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:reopen

**Comment by daviddotzhang** [comment]
Hi @rotty3000 

could you set a high priority on this PR ?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46522. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
