### PR TITLE
LPS-55725-MonitoringPortletToOSGI - merge

### PR DESCRIPTION
**Pull request by philipjones03**
@peterfellwock fyi

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28714. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/19728ba~2...19728ba) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
