### PR TITLE
LPS-69811 SF

### PR DESCRIPTION
**Pull request by dsanz**

### CODE REVIEW

**Comment by dsanz** [comment]
ci:retest

**Comment by dsanz** [comment]
ci:retest

**Comment by dsanz** [comment]
ci:reopen

**Comment by dsanz** [comment]
Hi @rotty3000, would you be so kind as to try to take a look to this one as soon as possible? I'm asking you this because this issue is blocking a fixpack release and this one took a bit longer than expected due to the retreat and the added tests.

Thank you in advance

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46723. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dsanz** [comment]
Thanks so much Ray, really appreciated!

**Pull request closed without merging**
