### PR TITLE
LPS-74319 Fixes MDR so multiple changes appear on UI

### PR DESCRIPTION
**Pull request by jrao**
LPS-74319 Fixes MDR so multiple changes appear on UI

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59242. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59467. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
