### PR TITLE
LPS-59894

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Ray, I'm sending you this to ask you to take a look on this commit: https://github.com/matethurzo/liferay-portal/commit/91afabb2850c76683b1369234f6a998aad5372bb

The rest I've reviewed but this is affecting the PortletPreferences and I think you are more up-to-date regarding that than I am.

Thanks,

Máté

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
@matethurzo can you rebase? I got merge conflicts. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Preston-Crary** [comment]
@rotty3000 if you are okay with this change I can rebase and send to whoever you would like.

**Comment by rotty3000** [comment]
as this never yet passed the CI tests, can you rebase this PR? No need for a new one, just update the branch you used to make this PR with your rebased changes.

**Comment by Preston-Crary** [comment]
@rotty3000 I'm not sure how to update someone else's pull request...

So I rebased the changes and resent them:

**Comment by rotty3000** [comment]
Please re-open if needed!

**Pull request closed without merging**
