### PR TITLE
LPS-57385 check individual scope permissions only when associated base model exists

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Closing because this impl is not appropriate.

**Comment by rotty3000** [comment]
pr-960 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
