### PR TITLE
LPS-79311

### PR DESCRIPTION
**Pull request by ChrisKian**
CC @gergelyszaz @JaredDomio @Joshuacords

https://issues.liferay.com/browse/LPS-79311

Forwarding to you since you reviewed the last iteration of LPS-79311.

From Josh:
> Changed ERROR to WARNING based on this discussion: liferay/liferay-portal-ee#6855 (comment)

Let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
This change should be safe; no need to test since it's just changing ERROR to WARN.

**Comment by joshuacords** [comment]
Hello @rotty3000, do you have an idea on when you'll be able to review this?

**Comment by rotty3000** [comment]
Hey guys, I approve of the change. Please forward it to Brian. Indicate that I've reviewed.

**Comment by joshuacords** [comment]
Thanks @rotty3000

**Comment by joshuacords** [comment]
Forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/59001

**Pull request closed without merging**
