### PR TITLE
LPS-75800

### PR DESCRIPTION
**Pull request by jrao**
LPS-75800 Allow protocol and port to be specified for sitemap.xml URL, not just hostname

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
ci:stop

**Comment by jrao** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59682. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59698. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/fcc2b3ed3d03~1...fcc2b3ed3d03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
