### PR TITLE
LPS-55156 - Migrate html/css/common into css module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hi Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-55156.

There is a plugins pull to go along with this one.  We have to do the same process as before with the git-commit-plugins file.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28002. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/1a28fd3~3...1a28fd3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28004. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/2b4c63b~3...2b4c63b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
