### PR TITLE
[TS] LPS-69649 Brackets are sometimes removed other times preserved when editing a custom field with Text type.

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-69649

Author: @amadeafejes
Reviewers: @lipusz

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest HEAD.

**Comment by lipusz** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46151. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
