### PR TITLE
[TECHNICAL-SUPPORT] LPS-57900

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Sorry could you rebase this please? Thx.

**Comment by jonathanmccann** [comment]
@ChrisKian looks like the code you were fixing was removed by LPS-57675. If this fix is still necessary, please resubmit it.

**Comment by ChrisKian** [comment]
/cc @jonathanmccann 

LPS-57675 has resolved this issue.  Feel free to close this pull request.  Thank you.

**Pull request closed without merging**
