### PR TITLE
[TECHNICAL-SUPPORT] LPS-66380

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @jgok @daniel-t-song

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by jgok** [comment]
ci:retest

**Comment by jgok** [comment]
These build errors appear to be unrelated to my fix, as the fix does not have any relation to modules or apps.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/40793. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
