### PR TITLE
LPS-59459 Search in the bundle and fragments

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
/cc @jbalsas 

Hey @rotty3000, 

please have a look at this patch. Can't find any better way to do this using OSGi API's. I understand this is "better" than using `getResource` because we don't need to look in the imports.

**Comment by csierra** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31065. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
