### PR TITLE
LPS-57826 Staging permissions

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

so here I tried to fix the staging permissions by:
1, checking permissions always on live groupId (wrapper around PermissionChecker)
2, creating teams in live groups (Advice around TeamLocalService)
3, defining site-related membership using live groupId 
... Advices around GroupLS and related LocalServices that are in 1:N relation
... Advices for M:N relations where group is present (User-Group-Role + UserGroup-Group-Role)

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Hey @topolik, sorry for the delay on this. But can you resolve the rebase error that we get with this? Thx :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi Ray

I talked to @matethurzo during Devcon that we have a design problem with Teams & Staging in context of permissions.

Staging propagates Teams (I understood this was a requirement) so they should be first created with staged groupId, then they are published to live => they are created with live groupId. But, because they are related to permissions, which should be checked only using live groupId, we wouldn't be able to check permissions that are assigned to Teams in staging.

I see two solutions but don't like any of them:
(1) Into PermissionChecker pass always the curent groupId - live / staging. Obtain live groupId for all checks and for Teams use the provided groupId (live / staging).
(2) Ignore teams for now and leave them broken

So I will probably go with (1), unless you or @matethurzo have any objections.

Thanks.

**Comment by topolik** [comment]
Please see https://github.com/rotty3000/liferay-portal/pull/1033. Thank you.

**Pull request closed without merging**
