### PR TITLE
LPS-52665

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey @rotty3000 

I'm sending this through you because you and Minhchau have already discussed this issue.

The first commit resolves the issue where the application server cannot find the ruby-gems.jar and the second commit fixes the issue where the lib and web portal directories are incorrectly set, which messes up parsing CSS files (among other things, I'm sure).

If you have any questions, please feel free to let me know. Also, including @holatuwol in case I missed anything.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
This looks like it introduces a concurrency issue in that multiple threads may all be setting up the gems at the same time. Constructor initialization is effectively synchronized and so that's why it was safe before. Moving this to a method makes it unsafe. There has to be some safety measure put in place. Please update. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonathanmccann** [comment]
Hey @rotty3000 

I updated the fix to use a synchronized block in order to mitigate the concurrency issue. Let me know if you had something else in mind.

Thanks.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/883. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
