### PR TITLE
LPS-55166 - Extract themes to independent frontend module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-55166.

This is related to the pull I sent you for plugins: https://github.com/rotty3000/liferay-plugins/pull/61.

The last commit is the link to that pull in the git-commit-plugins file so that jenkins will use that SDK.  We will have to revert that commit and update it with a plugins pull to brian like we did last time.  If you like I can take care of it once you review/make changes.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by kiyoshilee** [comment]
ci:retest

**Comment by mjbradford89** [comment]
I don't think this failure is due to my changes.  It looks like it's happening on all pulls.  I will rebase tomorrow and test again.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27498. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/cc1ff56~3...cc1ff56) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27499. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/4287eb6~3...4287eb6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
