### PR TITLE
LPS-109475 This is a minor schema version change because the change is required by the portal to work

### PR DESCRIPTION
**Pull request by achaparro**
See rules for schema version definition:
https://grow.liferay.com/people/Upgrade+Process+-+Schema+Version+Definition

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test

**Comment by ctampoya** [comment]
@achaparro / @rotty3000, please do not move forward with this fix.

**Comment by achaparro** [comment]
having this:
https://github.com/liferay/liferay-portal-ee/pull/18386

We can close this pull.

Thanks

**Pull request closed without merging**
