### PR TITLE
LPS-60085 - Update editor bundles translations when frontend-editor-lang is deployed

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-60085.

This is a much simpler solution than my last pull, thanks to help from @csierra and @jbalsas :).

One thing to note is that I left the `Include-Resource:content=../frontend-editor-lang/src/main/resources/content` lines in the editor bundle bnds, and then excluded *.properties files. I did this solely for the source formatter, as it complains that all the language keys are missing from these modules otherwise. The only other way around this is to make some changes to the source formatter so that it can find the lang keys in the editor-lang module.  If you think this is the route we should take, let me know and I can try and include it in this pull.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
:+1:

**Comment by csierra** [comment]
@mjbradford89 I personally like this one more. Thanks for asking our opinions!

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
rebased, fixed conflicts, and force pushed

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31994. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/2ca6ab3~1...2ca6ab3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
