### PR TITLE
LPS-59475

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @rotty3000 and @izaera!

In order to try building with Bnd 3, you need to:

1. install the new `gradle-plugins` in your local Maven repo: `gradlew install`
2. change `modules/build.gradle` to use new version, at line 15

I'm still making experiments with the manifest creation in `portal-bootstrap`, most likely it won't work...

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
I restarted this job on 10/15/15 at 12:26pm.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/Ithildir/liferay-portal/pull/103. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/20c9bd6~7...20c9bd6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1039. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/c5e2f6b~16...c5e2f6b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
