### PR TITLE
[TECHNICAL-SUPPORT] LPS-79012

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @mbowerman

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test

**Comment by SamZiemer** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I think this should be reviewed by @shuyangzhou who is much better acquainted with hinbernate's lower levels. However, otherwise I'm ok with this change.

One small point, is this method even used? I thought we removed usages of deprecated methods? Is this change being made in master only to qualify the logic which is intended for backport to 6.1?

**Comment by mbowerman** [comment]
Hi Ray,

As mentioned in the LPS description, the method is used by CounterFinderImpl._obtainIncrement (see https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/counter/service/persistence/impl/CounterFinderImpl.java#L369-L370).

**Comment by rotty3000** [comment]
Ok, sounds good! I still think @shuyangzhou should take a brief look.

**Comment by shuyangzhou** [comment]
Yes, please send it over to me. I will spend some time on it this week. Sorry, it won't be right away, long queue on my side right now. Thanks @rotty3000 for bringing it to me!

**Comment by SamZiemer** [comment]
@rotty3000 @shuyangzhou I'll send that over now, thank you.

**Comment by rotty3000** [comment]
@shuyangzhou I would have a voided putting this on you except that if this caused a regression it would likely fallen on you after when more damage was already done.

**Comment by shuyangzhou** [comment]
Yes, that makes sense. And I do want to take a look at this. Thanks @rotty3000 !

**Comment by SamZiemer** [comment]
I've created the pull request here: https://github.com/shuyangzhou/liferay-portal/pull/5916

**Pull request closed without merging**
