### PR TITLE
Providing the right versions for the exported packages

### PR DESCRIPTION
**Pull request by milendyankov**
I hope we can have this manual fix until we figure out how to automate the process if exporting the right package version of the embedded 3rd party packages?

### CODE REVIEW

**Comment by rotty3000** [comment]
There's work in progress to fix all the package versions.

**Comment by milendyankov** [comment]
Yea, I know. I was just hoping we could have a solution for this particular one now instead of waiting several weeks/months to allow people (GS in particular) to experiment/test further. But never mind.

**Comment by rotty3000** [comment]
I guess I can take it for now.

**Comment by milendyankov** [comment]
Is that what you meant?

**Comment by rotty3000** [comment]
exactly! Nice job! :)

**Comment by rotty3000** [comment]
Can you associate this with an LPS? PRs to Brian fail automatically if not associated with a ticket in JIRA, each commit must also be tagged with the LPS. Thx. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by milendyankov** [comment]
Thanks Ray. I Created an issue and associated this PR with it! Not sure if I can interactively rebase the branch to change the commit messages to include LPS number and how that affects the PR. Is that OK or should I open a new one?

**Comment by rotty3000** [comment]
You should be able to rebase interactively and change the commit comments
to start with the lps. Then just push to your github fork on the same
branch used to send me the changes. That auto updates the PR.

**Comment by milendyankov** [comment]
Done! It's cool that GitHub supports that. I would expect rewriting commit history to cause issues but it seams to work just fine!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33630. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/7236492~1...7236492) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
