### PR TITLE
LPS-64318 Simplify

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
This one passes all the tests! ;)

**Comment by csierra** [comment]
hey @rotty3000... is it possible that this fails in your master? It passed all tests on my master :confused: 
https://github.com/csierra/liferay-portal/pull/204

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37771. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
