### PR TITLE
Export the com.liferay.portal.spring.jndi package from portal-impl so that the JndiObjectFactoryBean class is made available to portal-spring-extender

### PR DESCRIPTION
**Pull request by jrao**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:reopen

**Comment by rotty3000** [comment]
@jrao this might need a rebase.

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51406. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Hey @jrao  can you put the JIRA ticket issue in the commit message?

**Comment by jrao** [comment]
@rotty3000 Done. Is a retest required?

**Comment by rotty3000** [comment]
nope!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51408. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
