### PR TITLE
LPS-63021 Create default SCOPE_INDIVIDUAL ResourcePermission records for each <model-resource> so that portal can check general ENTITY.ACTION (User.VIEW) without having real entity (User)

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

https://issues.liferay.com/browse/LPS-63021

I didn't know it but on several places in portal we check model permissions without having individual primary key.

For example we have `permissionChecker.hasPermission(0, User.class.getName(), companyId, Action.VIEW)` to know if user has assigned a company scoped permission to view all users. Which now obviously doesn't work, because there is no SCOPE_INDIVIDUAL record with primary key == companyId.

So I solved it the same way you did for portlets - created a default SCOPE_INDIVIDUAL record for the models. This fixes also https://issues.liferay.com/browse/LPS-51807.

Uhm, now I see the commit message related to `AdvancedPermissionChecker.fixLegacyPrimaryKey()` may be confusing, because I first fixed LPS-63020 (will be next PR). Let me please know if I should rephrase it. 

Thanks!

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
Test fail unrelated.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36181. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
