### PR TITLE
LPS-53825 Friendly URL beginning with the same string as proxy path is filtered wrong

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Ray,

we are really not sure if this modification can be done without any side-effect, however, we cannot see which that code snippet is necessary; our tests don't show any problem.

It could be a case only if the friendly url contains the context path which, I think, shouldn't be a case, however I might be wrong. Might that be there because of some legacy case? Nevertheless, it definitely cause a problem in the latest versions if the friendly url of a page starts with the context path in its name.

Could you please take a look at.

Thank yin advance,
Zsigmond

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Have you verified this when the portal is running in a different context\? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Any word on this?

**Comment by zsolah** [comment]
Hi Ray,

Testing with changed context turned out my fix causes problems. So in this form this is not applicable. 
We are analyzing the issue. Please close this pull request.

**Pull request closed without merging**
