### PR TITLE
LCD-14473 - Provide OAuth2Client via import and global

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey, I believe this should fix all the TS related issues you were having. I PM'd you on slack but I will include my questions here too.

1. Would be it weird to not provide OAuth2Client on the global Liferay object and only provide it via a JS import? Or would this not work with a common use case of client extensions?

2. Why is OAuth2Client a class? You never call `new` or utilize the constructor. Can it just be a plain object?

### CODE REVIEW

**Comment by rotty3000** [comment]
reviewing..

**Comment by bryceosterhaus** [comment]
@rotty3000 just updated PR, let me know if you have any questions

**Comment by rotty3000** [comment]
I tried to rebase this on master and when I build I get:
```
portal-master]$ (cd modules/ && gw :apps:item-selector:item-selector-taglib:packageRunBuild)
Configuration on demand is an incubating feature.
> Task :downloadNode UP-TO-DATE
> Task :apps:item-selector:item-selector-taglib:downloadNode UP-TO-DATE
> Task :apps:item-selector:item-selector-taglib:npmInstall SKIPPED

> Task :yarnInstall
yarn install v1.13.0
[1/4] Resolving packages...
warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
success Already up-to-date.
Done in 1.31s.

> Task :apps:item-selector:item-selector-taglib:packageRunBuild
yarn run v1.13.0
warning package.json: No license field
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: "production"
../../oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts(32,40): error TS6059: File '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/OAuth2Client.ts' is not under 'rootDir' '/home/rotty/projects/portal-master/modules/apps/item-selector/item-selector-taglib'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via './OAuth2Client' from file '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts'
    Imported via './OAuth2Client' from file '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts'
../../oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts(32,40): error TS6307: File '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/OAuth2Client.ts' is not listed within the file list of project '/home/rotty/projects/portal-master/modules/apps/item-selector/item-selector-taglib/tsconfig.json'. Projects must list all files or use an 'include' pattern.
  The file is in the program because:
    Imported via './OAuth2Client' from file '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts'
    Imported via './OAuth2Client' from file '/home/rotty/projects/portal-master/modules/apps/oauth2-provider/oauth2-provider-web/src/main/resources/META-INF/resources/js/liferay.d.ts'
Command /home/rotty/projects/portal-master/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/tsc --emitDeclarationOnly exited with code 2
Received 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Task :apps:item-selector:item-selector-taglib:packageRunBuild FAILED


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:item-selector:item-selector-taglib:packageRunBuild'.
> Process 'command '/home/rotty/projects/portal-master/build/node/bin/node'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Comment by rotty3000** [comment]
FYI that is the specific error. The error from `ant all` is much less specific but originates from the same place.

**Comment by rotty3000** [comment]
oh btw, besides that, this is looking really great. I think this is the model to move forward with.

**Pull request closed without merging**
