### PR TITLE
LPS-55156 - Migrate html/css/common into css module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-55156.

You've already reviewed most of this pull, but I had to make some more changes to fix a few conflicts and some things breaking in plugins.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28770. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
