### PR TITLE
LPS-61596 - Extract liferay-look-and-feel.xml to individual theme bundles

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-61596.

The idea here was to extract the look-and-feel xml definitions into the individual theme bundles.  But because of the way the portal is initialized I had to create a service dependency listener for a couple things (fae1855, and 617ba6b).

@peterfellwock already reviewed this as well.

Please let me know your thoughts.

Thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
This change introduces a sync on the OSGi runtime. We've removed all those from other places already. It would probably be better to use a whiteboard pattern that detects if no page themes are deployed and display a status page to that effect. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
Thanks for taking a look at this Ray.  I'll give this another shot leveraging a whiteboard pattern next week.

**Comment by mjbradford89** [comment]
Hey @rotty3000,  is there an example of a whiteboard pattern in portal you could point me to so I can get a better idea of the concept? Thanks!

**Pull request closed without merging**
