### PR TITLE
LPS-57218 - Adjust CSSBuilder parse logic to not rely only on a CSS directory name to compile sass

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by peterfellwock** [comment]
@mjbradford89 Wohoo!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28710. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
