### PR TITLE
[TS] LPS-83222

### PR DESCRIPTION
**Pull request by yuhai**
Hi Ray,

Hope you are well.

The PR extends from https://github.com/rotty3000/liferay-portal/pull/1407 to solve the test error(https://github.com/hhuijser/liferay-portal/pull/3343#issuecomment-402712809).

Please refer to the fix explanation from https://github.com/hhuijser/liferay-portal/pull/3343#issue-199429220

cc @hhuijser

Regards,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi @rotty3000 

Hope you are well.

Sorry, https://github.com/brianchandotcom/liferay-portal/pull/61161 will cause the test failed. Please review this PR, instead of using https://github.com/brianchandotcom/liferay-portal/pull/61161 (https://github.com/rotty3000/liferay-portal/pull/1407).

Regards,
Hai

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
Hi @rotty3000 

@shuyangzhou submitted one PR to solve this. I will close this PR.
Please see https://github.com/brianchandotcom/liferay-portal/pull/61181

Regards,
Hai

**Pull request closed without merging**
