### PR TITLE
Portlet Tracker: modified portlets

### PR DESCRIPTION
**Pull request by migue**
Ray, feel free to implement this solution in a completely different approach, just wanted to highlight the problems that, potentially could arise when doing remove/add on a modifiedService invokation

### CODE REVIEW

**Comment by jpince** [comment]
ci:reopen

**Comment by jpince** [comment]
@rotty3000 can you please take a look at this? We had to turn off all XSL and XSS tests for this, as the shutdown error was causing our CI builds to abort.

Looks like adjusting where the line break occurs will resolve the SF issue:
```
expected:<...et newPortletModel =[ addingService(
			]serviceReference);

but was:<...et newPortletModel =[
			addingService(]serviceReference);
```

Thanks @migue!
cc/ @anthony-chu @alee8888

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44904. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
