### PR TITLE
LPS-57385 check if the first resource is a model-resource and if not, skip individual scope check

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I don't think this change is acceptable, because it should be possible for non-models to have permissions applied, provided they create an initial resource before performing permission checks.

**Comment by rotty3000** [comment]
see earlier comment. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
