### PR TITLE
LPS-54156 XML vulnerabilities in OSGi

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

I took your pull request and secured it against XML Bomb attack, which was missing.

Thank you.

### CODE REVIEW

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
Hi Ray,

it seems SourceFormatter and its test are out of sync. Do you know how to fix it?

Thanks

**Comment by rotty3000** [comment]
not really...

Don't worry about this. I can review it like this.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25498. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
