### PR TITLE
LPS-54998 - performance regression fix

### PR DESCRIPTION
**Pull request by mjbradford89**
Hi Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-54998.

This contains commits reverting the reverts, plus a commit (5f6e6e52de3df805da847a3143c714af77df5d19) to fix the performance regression.  Lily Chi ran the performance benchmarks and got these results (top row is the this pull):

image

So I think everything looks good.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Nice work @mjbradford89! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25979. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
