### PR TITLE
LPS-54558 We are using File.mkdirs() method without checking its return value

### PR DESCRIPTION
**Pull request by laszlocsontos**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
Hi @rotty3000 @laszlocsontos 

Do you have any update about this?

Thank you

**Comment by rotty3000** [comment]
I was away the past two weeks. I will try to review again this week.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26418. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
