### PR TITLE
LPS-65786 use field injection just to clean this up a little

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@peterfellwock testing this here...

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by peterfellwock** [comment]
@rotty3000 this has the patching mechanism which we are not using anymore. You're pull https://github.com/rotty3000/liferay-portal/pull/1249 is more accurate.

**Comment by rotty3000** [comment]
yup, this is closed

**Pull request closed without merging**
