### PR TITLE
LPS-64093

### PR DESCRIPTION
**Pull request by juangon**
Hi @rotty3000. Seems yesterday's commit (https://github.com/brianchandotcom/liferay-portal/pull/38013/commits/706318f59fd23b28e6527bdd0ba6c2a9266a3a7c) broke the context-param assembling logic for web-fragment from this pull request.

The issue is web-fragments should be sorted using an algorithm, and now, unless that sorting logic is duplicated in servlet context helper or create some kind of @Component to do that, it won't work. 

Please, try to fix that on top of my PR.

Thanks!

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38099. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/38a2e5f~42...38a2e5f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38263. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/7a0c8e90~44...7a0c8e90) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38330. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/fb0c962~17...fb0c962) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38331. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/331f9cc~16...331f9cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
