### PR TITLE
Extracted standalone Metatype API bundle

### PR DESCRIPTION
**Pull request by milendyankov**
Hi Ray,

as discussed this is extracted Metatype API. Hope I did it right ;) but anyway shouldn't be too hard nor long to check ;)

### CODE REVIEW

**Comment by rotty3000** [comment]
This looks good. Can you add equinox metatype (sent you coordinates) to this ivy.xml and then tell build.xml to publish both to `${liferay.home}/osgi/portal`? See `modules/portal/portal-servlet-jsp-compiler/build.xml` for an examples.

**Comment by rotty3000** [comment]
Oh, and I guess we have to make sure not to publish the felix.metatype. Can you change that reference down and remove it.

**Comment by milendyankov** [comment]
I'm not 100% sure this is what you meant, but please have a look.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
We don't need to do this anymore since the metatype companion bundle is now available individually packaged. :) Thx! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
