### PR TITLE
LPS-57568 Suscribing in Asset Publisher does not send emails

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28937. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
