### PR TITLE
LPS-53563

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I don't think I can accept this change due to the removal of
```
		if (resourcePermissionPersistence.countByC_N_S_P(
				firstResource.getCompanyId(), firstResource.getName(),
				firstResource.getScope(), firstResource.getPrimKey()) < 1) {

			return false;
		}
```

**Comment by Preston-Crary** [comment]
@rotty3000

I tested LPS-47464, LPS-50147 seems to have resolved the issue in a different way that doesn't break permissions that do not have individual scope.  Are there other reasons this needs to be here?

**Comment by rotty3000** [comment]
Yeah, there is! Every resource should have an individual scope
resourcePermission!

**Comment by Preston-Crary** [comment]
Got it, thanks for the clarification.  I'll work on it from that direction then.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Closing for now.

**Comment by Preston-Crary** [comment]
Resent https://github.com/rotty3000/liferay-portal/pull/722

**Pull request closed without merging**
