### PR TITLE
LPS-62989

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
3 files need to be fixed.
You mind looking at those, since you can fix those MUCH faster than me?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Looks Good! You can send to Brian. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
@rotty3000

Do you mind looking at those 3 files that need to be rewritten? Not too familiar with all of this myself. I figure it would take me some time to figure it out.

- modules/apps/portlet-configuration/portlet-configuration-toolbar-contributor-locator-api/src/main/java/com/liferay/portlet/configuration/toolbar/contributor/locator/BasePortletToolbarContributorLocator.java
- modules/core/jaxws-osgi-bridge/src/main/java/com/liferay/jaxws/osgi/bridge/Provider.java
- modules/portal-search/portal-search/src/main/java/com/liferay/portal/search/internal/result/SearchResultManagerImpl.java

**Comment by hhuijser** [comment]
Hey @rotty3000, can you look at this?

**Pull request closed without merging**
