### PR TITLE
Some things I have seen around PortletTracker

### PR DESCRIPTION
**Pull request by csierra**
This is not for merging it, just assorted things I have found while investigating other stuff. Please tell me what your opinion is on these matters. 

Regards.

### CODE REVIEW

**Comment by csierra** [comment]
/cc @migue

This has some of the things we have been discussing. Just FYI.

**Comment by csierra** [comment]
don't pay attention to the failing tests for the moment. It looks like we were relying on the order of registration of the services. IMHO we shouldn't do that, because that is not something we can necessarily control, is it?

**Comment by rotty3000** [comment]
We certainly should not rely on ordering.

**Comment by csierra** [comment]
hey @rotty3000 

I have changed some things around and certainly some improvements can be made in `ResourceBundleTracker` to build the ResourceBundles on arrival instead on request time. 

We seemed to be caching references and then mutating them underneath... I personally would avoid that and prefer this situation. 

Let me know what you thoughts are. Anyhow we would need to do something if we fix the portlet tracker because, with what is in master, some portlets did not work after the fix.

**Comment by csierra** [comment]
ci:retest

**Comment by csierra** [comment]
ci:retest

**Pull request closed without merging**
