### PR TITLE
LPS-53132

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
This pull request avoids a malformed SQL with a empty "()" in some situations: 
   `....peId)) AND (() OR (dlFileEn.....`
See first commit https://github.com/jorgediaz-lr/liferay-portal/commit/d344e7b9ce5b81841cde2cd0e3c579dafd586a91

After this modification, I have realized that there is some unnecessary code:
      - The permission check is not necessary because both if and else code are the same
      - This code was modified at following issues: LPS-43611, LPS-45001, where some different code was removed at IF side

I have simplified the code at the rest of commits

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
There are some pending tests

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@jorgediaz-lr can you rebase? Perhaps that might resolve the failures.

**Comment by jorgediaz-lr** [comment]
I am closing this pull request because code at https://github.com/jonathanmccann/liferay-portal/pull/587 includes the solution to this issue.

**Pull request closed without merging**
