### PR TITLE
LPS-56537 - Extract frontend-editors-web to individual editor modules

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-56537.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @rotty3000 what's the status of this PR? Are we planning to merge it?

I haven't looked inside, but I think it could be a good thing if we're able to land it so we could evolve the different editors independently... I could help you guys review it or check that everything works if you need me to.

Thanks!

**Comment by rotty3000** [comment]
I'm just back at my office today so I will try to get it reviewed ASAP
(which means sometime in the next few days).

Sincerely,
- Ray

On Tue, Oct 13, 2015 at 4:21 PM, Chema Balsas <notifications@github.com>
wrote:

> Hey @rotty3000 <https://github.com/rotty3000> what's the status of this
> PR? Are we planning to merge it?
>
> I haven't looked inside, but I think it could be a good thing if we're
> able to land it so we could evolve the different editors independently... I
> could help you guys review it or check that everything works if you need me
> to.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/liferay-portal/pull/1004#issuecomment-147840813>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mjbradford89** [comment]
@rotty3000 This pull probably has some conflicts now.  When I get a chance today I will rebase and resolve them and force push.  Thanks!

**Comment by mjbradford89** [comment]
@rotty3000 rebased and fixed the conflicts :)

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I think it needs to be done again!!! I got a rebase failure.

On Thu, Oct 15, 2015 at 1:40 PM, Michael Bradford <notifications@github.com>
wrote:

> @rotty3000 <https://github.com/rotty3000> rebased and fixed the conflicts
> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/liferay-portal/pull/1004#issuecomment-148468814>
> .
>



-- 
*Raymond Augé* <http://www.liferay.com/web/raymond.auge/profile>
 (@rotty3000)
Senior Software Architect *Liferay, Inc.* <http://www.liferay.com>
 (@Liferay)
Board Member & EEG Co-Chair, OSGi Alliance <http://osgi.org> (@OSGiAlliance)

**Comment by mjbradford89** [comment]
Dang :(. working on it now.

**Comment by mjbradford89** [comment]
Ok resolved again.  Hopefully for longer this time :)

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31069. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/b030d95~1...b030d95) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
