### PR TITLE
[TECHNICAL SUPPORT] LPS-63922 User-specific portlet preferences are not cleaned up when the portlet is removed and portlet can not be re-added

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-63922

Hi Ray,

See Norbert's comment:
>Use cases to consider:
1. Preferences-unique-per-layout=true preferences-owned-by-group=true
plid+portletId will be unique in this case and that record should be removed.
2. Preferences-unique-per-layout=true preferences-owned-by-group=false
This is what the issue is about. In this case there will be one record for the layout owned by the group, and one owned by each user who configures the portlet. Every one of those needs to be removed.
3. The column is customizable.
plid+portletId will be unique (portletId + userId separator + userId) in this case and that record has to be romoved

>In other cases the preferences won't be related to the layout so they won't be removed.

I've asked him to create a test for this. We'll submit if you agree with his changes.

Thanks,
Tibor

/cc @NorbertKocsis

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
rebased

**Comment by lipusz** [comment]
Rebased.

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Hi Ray,

After a long and fortunately productive dev lead retreat, do you think you can proceed with this during this week?

We'd like to backport this to 62x as soon as possible so we can release in a fix pack, but we cannot unless it's not in master.

Thanks,
Tibor

@rotty3000

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38663. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
