### PR TITLE
LPS-59894 Fix performance issues with page versioning and admin user's preferences

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Can you send this to the staging team please?

**Comment by Preston-Crary** [comment]
Sure:
https://github.com/matethurzo/liferay-portal/pull/1275

**Pull request closed without merging**
