### PR TITLE
LPS-53865 Use UserPermissionCheckerBag to avoid complex RoleFinder join

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
Hey @holatuwol, as you can see the tests fail. You may want to look at it and resend the pull to Ray after fixing the issues. If you think they are unrelated add a comment with the text ci:retest to run them again.

**Comment by holatuwol** [comment]
I didn't do anything that would affect subscriptions, but our testing framework is pretty fragile. To eliminate the possibility that it's my fixes, I've submitted https://github.com/rotty3000/liferay-portal/pull/742 which is identical to this but without my fixes.

```
git fetch git@github.com:rotty3000/liferay-portal.git pull/741/head:test-rotty3000-741-withoutchanges
git checkout test-rotty3000-741-withoutchanges
git reset --hard HEAD~4
git push origin test-rotty3000-741-withoutchanges
```

This will allow the CI server to re-run the tests and see if the failure is a result of my fixes or are a result of something else that's already broken in master but unrelated to my fixes.

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
Since https://github.com/rotty3000/liferay-portal/pull/741 fails these tests but https://github.com/rotty3000/liferay-portal/pull/742 passes them, there is some weird dependency going on here that has to be resolved. I'll resend after figuring out what that is.

**Comment by holatuwol** [comment]
@JorgeFerrer can you go ahead and close this pull request?

**Comment by JorgeFerrer** [comment]
Closing, as requested by @holatuwol

**Pull request closed without merging**
