### PR TITLE
LPS-73245

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
For more info: https://github.com/hhuijser/liferay-portal/pull/2890

**Comment by yuhai** [comment]
Hi @rotty3000,

Hope you are well.

Since the issue came from EE customer. Could you please review this PR when you have time?

Regards,
Hai

**Comment by yuhai** [comment]
Hi @rotty3000 

Hope you are well.

I'm wondering if you had a chance to review this PR. Please feel free to let me know if there are any questions.

Regards,
Hai

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50081. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
