### PR TITLE
LPS-53563

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Solved by https://github.com/brianchandotcom/liferay-portal/pull/24510 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
