### PR TITLE
LPS-54505 - Extract CSS from portal-web into front-end module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Ray,

Attached is an update for https://issues.liferay.com/browse/LPS-54505.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Sorry to spam you with all these failing pulls.  I'll let you know when I have this plugins-sdk issue figured out.

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
Hey @rotty3000 
Sorry for all the retesting.  But it is now ready to be reviewed along with https://github.com/rotty3000/liferay-plugins/pull/57.

Thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26987. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
