### PR TITLE
LPS-60997 - FriendlyURLMapperTrackerImpl is using the wrong classloader to load routes.xml

### PR DESCRIPTION
**Pull request by milendyankov**
Hi Ray, here is a fix for the issue we discussed earlier. I hope this is the right way to fix it.

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
This change is good. Could you please add a portlet-container-test which asserts this works? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by milendyankov** [comment]
Could you please explain in a bit more details what test exactly you have in mind? Do you mean to start the portal, simulate deploying a bundle with FriendlyURLMapper extension point implementation and check the classloader? If so, does this still belong to 'portlet-container-test' (as it does not strictly deals with portlets but rather bundles)? Anything similar to use a reference?

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/33632. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
