### PR TITLE
LPS-73754 SF

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:reopen

**Comment by almonwork** [comment]
Hi @rotty3000 

This PR has been stuck for 7 seven days. As this could be a security risk, it is important to move it forward quickly. When would you be able to work on this?

Regards
  Alberto

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50625. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50626. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/5b7d7351500b~1...5b7d7351500b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
