### PR TITLE
LPS-61748 Include transitive dependencies in Bnd

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Looks good! Can you forward this to Brian? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
... might need to be rebased and retested.

**Comment by Ithildir** [comment]
Ok, I'll send it to him! :blush:

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
oops.. .that won't really help

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
