### PR TITLE
LPS-74339

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @rotty3000,

First off, this pull depends on https://github.com/rotty3000/liferay-portal/pull/1350

Secondly, I'm not entirely sure the best way to resolve this issue. As far as I can tell we have three options:

1. Do not cache the filter chain if there is a query string present (option presented in this pull request)
2. Cache the filter chain with the query string appended to the URI
3. Do not match regex against query string (remove https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/servlet/filters/invoker/FilterMapping.java#L127-L131)

I can see benefits and drawbacks to all of these options. Please let me know your thoughts and if you have any questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
@rotty3000 Is there any update on this pull?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/51262. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
