### PR TITLE
LPS-53485

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
CC @Preston-Crary I don't think these tests are dealing with what you changed, but let me know if this needs to be resent.

**Comment by Preston-Crary** [comment]
These are not relevant to what I changed.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/24011. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
