### PR TITLE
LPS-59475 gradle-plugins

### PR DESCRIPTION
**Pull request by Ithildir**
Hi @rotty3000!

Here is an updated version of `gradle-plugins` with Bnd 3.0. The WSDD part can probably be better, but it should work! I wanted to send you something as soon as possible, so you could keep going!

The pull contains a few commits (the `LPS-60280` ones) that are [currently](https://github.com/brianchandotcom/liferay-portal/pull/32134) in review. You'll need them in order to try the new `gradle-plugins`.

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Ithildir** [comment]
Hi @rotty3000!
I rebased this branch on top of master, it should be ok..

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
closing this for now since there have been many incompatible updates <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
