### PR TITLE
LPS-57261

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @rotty3000,

Attached is an update for http://issues.liferay.com/browse/LPS-57261. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/mjbradford89/liferay-portal/pull/51. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/e0e3267~1...e0e3267) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
