### PR TITLE
Lrqa 75397

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant
ci:test:sf

**Comment by susanchen3** [comment]
Hey @rotty3000 these tests are still failing

- [com.liferay.portal.k8s.agent.internal.test.PortalK8sAgentImplTest](https://testray.liferay.com/home/-/testray/case_results/1897291572?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1897264911%26testrayRunId%3D1897281503%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
- [com.liferay.portal.k8s.agent.internal.mutator.test.LabelsPortalK8sConfigurationPropertiesMutatorTest](https://testray.liferay.com/home/-/testray/case_results/1897291570)
with
```
     [exec] com.liferay.portal.k8s.agent.internal.mutator.test.LabelsPortalK8sConfigurationPropertiesMutatorTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.k8s.agent.test [1502]
     [exec]       Unresolved requirement: Import-Package: io.fabric8.kubernetes.client.server.mock; usage="test"
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
     [exec] 
     [exec] com.liferay.portal.k8s.agent.internal.mutator.test.AnnotationsPortalK8sConfigurationPropertiesMutatorTest > classMethod STARTED
     [exec] 
     [exec] com.liferay.portal.k8s.agent.internal.mutator.test.AnnotationsPortalK8sConfigurationPropertiesMutatorTest > classMethod FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.SocketState.writeUTF(SocketState.java:123)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.client.ClientState$1.execute(ClientState.java:127)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.run(Arquillian.java:123)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

**Comment by rotty3000** [comment]
yep :)

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
[com.liferay.portal.k8s.agent.internal.mutator.test.AnnotationsPortalK8sConfigurationPropertiesMutatorTest](https://testray.liferay.com/home/-/testray/case_results/1897447025) is still failing unfortunately :\ 

```
     [exec] com.liferay.portal.k8s.agent.internal.mutator.test.AnnotationsPortalK8sConfigurationPropertiesMutatorTest > classMethod FAILED
     [exec]     org.osgi.framework.BundleException: Could not resolve module: com.liferay.portal.k8s.agent.test [1500]
     [exec]       Unresolved requirement: Import-Package: io.fabric8.kubernetes.client.server.mock; usage="test"
     [exec]         at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec]         at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.FrameworkCommand.lambda$startBundle$37e16ea2$1(FrameworkCommand.java:46)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.connector.ArquillianConnectorThread.run(ArquillianConnectorThread.java:82)
     [exec] There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/modules/apps/static/portal-k8s-agent/portal-k8s-agent-test/build/reports/tests/testIntegration/index.html
```

**Comment by susanchen3** [comment]
ci:test:bundle

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
Looks like its passing in this latest run, going to run relevant again to check if it was fluke

**Comment by susanchen3** [comment]
didnt run the k8s tests

**Comment by susanchen3** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
recent CI changes aren't reading the test.properties file

**Comment by susanchen3** [comment]
ci:test:relevant

**Pull request closed without merging**
