### PR TITLE
LPS-55209 - Create an ant task in modules that will deploy without running all dependent task

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
@mjbradford89 fyi

**Comment by mjbradford89** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
How is this different than 'ant deploy'? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
Hi @rotty3000,

The reason behind wanting this task in there is because some front end developers will make changes to alloy in portal, and want to test those changes out without having to do a 'ant release' in alloy and then dropping the zip in third-party, and then re deploying the module.  With this task they can just make changes to alloy in the /tmp dir, and then run ant deply-static-files and see their changes immediately.  If just ant deploy is run, the changes made in /tmp won't be deployed because it looks like no changes were made.

If you think this isn't a good idea to have this task in there, I'm sure they can adjust their workflow.  Or I can send them the task and they can keep it in their own build file without committing it.

**Comment by rotty3000** [comment]
Just do ant clean deploy?

**Comment by mjbradford89** [comment]
@rotty3000  ant clean deploy will delete the tmp directory containing the dev's changes

**Comment by rotty3000** [comment]
Ok!

**Comment by peterfellwock** [comment]
@rotty3000 Can this be merged then?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26415. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
