### PR TITLE
LPS-54442

### PR DESCRIPTION
**Pull request by dustinryerson**
@Preston-Crary

### CODE REVIEW

**Comment by dustinryerson** [comment]
ci:retest

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Guys I'm going to close this PR and ask you to resend it after the extracted shopping portlet is merged back into core. /cc @Preston-Crary <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
