### PR TITLE
LPS-54558 We are using File.mkdirs() method without checking its return value

### PR DESCRIPTION
**Pull request by laszlocsontos**
/cc: @sergiogonzalez

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
@laszlocsontos 

About this modification: https://github.com/laszlocsontos/liferay-portal/commit/92c9db942f12dfc4b0dd3785b33497a86947fa82#diff-88ac7be5a8784b58a2c7ce72733632b5

You have added a check **if (path.exists()) {** but path can exists and not being a directory.
At apache commons FileUtils.forceMkdir, that is used at new *mkdir(File)* method they already do that check:
  - https://commons.apache.org/proper/commons-io/javadocs/api-2.1/src-html/org/apache/commons/io/FileUtils.html#line.2006

I think it will be better to remove it delegating this check to FileUtils.forceMkdir or do the same check: **if (path.exists() && path.isDirectory()) {**

Thank you

**Comment by laszlocsontos** [comment]
Thanks @jorgediaz-lr, I've just applied your suggestion.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Might I suggest not putting a `SystemException` wrapper in so many places?

What would happen if you used `com.liferay.portal.kernel.util.ReflectionUtil.throwException(Throwable)`?

This would allow you to avoid the wrappers without declaring a throws.

**Comment by laszlocsontos** [comment]
Hi Ray,

Sorry, I've just reached here. I'll send a new PR shortly.

Cheers,
László

**Comment by laszlocsontos** [comment]
https://github.com/rotty3000/liferay-portal/pull/809

**Pull request closed without merging**
