### PR TITLE
LPS-52097

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@jonathanmccann can you rebase this and see if it passes?

**Comment by jonathanmccann** [comment]
Hey @rotty3000 I have rebased the branch. I'll trigger the test again since I'm not sure if yours will catch the updated branch or not.

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
Looks like the errors aren't resolved with a rebase, but none of the errors are dealing with code that I changed. Let me know how you'd like to proceed.

**Comment by rotty3000** [comment]
yup, they look unrelated!

Will review shortly.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Please use the new configuration pattern for modules. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lipusz** [comment]
Hi @jonathanmccann

I saw Angelo's post in SO.
I think, Ray expects something similar to this:
https://github.com/lipusz/liferay-portal/pull/60

**Comment by jonathanmccann** [comment]
Hi @lipusz 

Thanks for pointing that out. I was hoping for some documentation on OSGi in general (specifically relating to programming guidelines to follow on pull requests so that we don't run into this again), but I have enough to fix up this pull.

Thanks.

**Comment by lipusz** [comment]
Hi Jonatha, 

We have hundreds of thousands of lines in our documentation maintained at liferay/liferay-portal#master.

It's always up-to-date. 😀 😀

**Pull request closed without merging**
