### PR TITLE
LPS-56065 Portal Settings portlet to OSGI

### PR DESCRIPTION
**Pull request by philipjones03**
@peterfellwock fyi

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29533. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/1c86c0a~1...1c86c0a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29545. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/aa9a75f~2...aa9a75f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by philipjones03** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
