### PR TITLE
LPS-60355 caches

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
ci:retest

**Comment by juangon** [comment]
Hi @rotty3000, please can you prioritize this pull if possible? I have other pull almost ready for https://issues.liferay.com/browse/LPS-58355 that will conflict with some of these commits so I need this pushed to master to fix it in advance.

Thanks very much!

**Comment by rotty3000** [comment]
Can you modify the test to express that the exception is logged? Look for examples of doing this in portal-portlet-container-tests. This way CI will not fail it.

**Comment by csierra** [comment]
Hey @rotty3000,

this is not because of the test, this is caused because before this pull the resource was pulled from portal-impl, and now it is not. Every test that registers a portlet without the resource will cause this and, if I understood correctly, we should go through every test saying it will cause this. I would rather change the util and make it issue file an INFO.

**Pull request closed without merging**
