### PR TITLE
LPS-56578

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by bejondshao** [comment]
Hey @rotty3000 ,

Would you take some time to review this?

Thanks
Bejond

**Comment by hhuijser** [comment]
Hey @rotty3000 

Can you review this? It's customer related, so it would be great if you give this priority...

**Comment by rotty3000** [comment]
Just got back from being away for a week.

**Comment by hhuijser** [comment]
Sent to Eudaldo instead: https://github.com/ealonso/liferay-portal/pull/438

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27996. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
