### PR TITLE
LPS-56537 - Extract frontend-editors-web to individual editor modules

### PR DESCRIPTION
**Pull request by peterfellwock**
From @mjbradford89

Hey Peter,

Attached is an update for https://issues.liferay.com/browse/LPS-56537.

These changes split the frontend-editors-web bundle into separate modules for each editor. I had to change the way InputEditorTag and our Editor.java files work in order to accomplish this.

Instead of the Editor files extending BaseEditor, now they just directly implement Editor and BaseEditor is no more. I did this because the one common method in BaseEditor is now longer needed. Please let me know your thoughts.

Thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Sorry, could you rebase this please? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
@peterfellwock @rotty3000 

I will pull down, rebase, and resend, but I think there will be significant changes needed now for the new gradle build. I'm doing the same for themes now, so it may be a while before I resend.

**Comment by mjbradford89** [comment]
New pull submitted: https://github.com/rotty3000/liferay-portal/pull/1004

**Pull request closed without merging**
