### PR TITLE
LPS-76000 Add support for null JSON objects

### PR DESCRIPTION
**Pull request by jrao**
LPS-76000 Add support for null JSON objects

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by jrao** [comment]
ci:test

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59675. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/1e0d96b47745~1...1e0d96b47745) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/59676. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/7f0a270e03c0~2...7f0a270e03c0) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
