### PR TITLE
LPS-52658

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey @rotty3000 can we make the bnd cleaner? It seems quite verbose right now for all those DTDs? Thx.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
can we leave it like this until we have a plugin for bnd to automate it? This syntax is a spec, not something I made up. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23317. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
