### PR TITLE
LPS-52297 Handle OPTIONS request with NOT IMPLEMENTED HTTP Status code

### PR DESCRIPTION
**Pull request by vilmospapp**
Hi Ray,

Based on your feedback received by @laszlocsontos via e-mail, I've implemented the solution you mentioned with one modification. We discovered, that Sharepoint integration and WebDAV deals with OPTIONS requests, so I moved the URI checking from SharepointFilter to ServletRequestUtil and let the OPTIONS request go through InvokerFilter only when the URI matches the Sharepoint or WebDAV urls.

Please review my changes,

Regards,
Vilmos

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@vilmospapp this seems to be causing some socket timeouts.

**Comment by rotty3000** [comment]
shall I close this PR?

**Comment by vilmospapp** [comment]
Hi Ray,

I'm currently testing it with Weblogic, so I'll close it for now, to clean up your queue until I can fix that socket timeout as well.

Regards,
Vilmos

**Pull request closed without merging**
