### PR TITLE
[TS] LPS-86754

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-86754

Hi @rotty3000 ,

## Context
This pr is for the issue we discussed regarding **org.apache.felix.fileinstall** having a dependency on **org.apache.felix.configadmin** to include the class: **ConfigurationHandler.java**.
- Reference: https://github.com/apache/felix/blob/trunk/fileinstall/pom.xml#L155-L158

Liferay currently uses **org.apache.felix.fileinstall**, version: 3.5.4.
This version has a dependency on **org.apache.felix.configadmin**, version: 1.2.8.

## Issue
Currently, we use **org.apache.felix.fileinstall** to read configuration files residing in **osgi/configs**.
The issue is that **org.apache.felix.configadmin**, version: 1.2.8, does not support comments. 

This causes an issue for Liferay's mechanism of storing configurations in the database and restoring them from the database.

Currently, **configuration entries with comments** that are stored in the database **cannot be properly retrieved**. This causes orphaned configuration entries and the following regression bug: [LPS-86673](https://issues.liferay.com/browse/LPS-86673)

## Proposed Fix
As discussed, our change will include an updated version of **ConfigurationHandler.java** by copying the class directly from a newer version of **org.apache.felix.configadmin**.

This issue has been fixed by [FELIX-4917 : FilePersistenceManager doesn't support comments](https://github.com/apache/felix/commit/2d774bf287d00ea55a534b8c0382819ab5e07489), which was included in **org.apache.felix.configadmin**, version: 1.8.8.

For our fix, we are adding a dependency for **org.apache.felix.configadmin**, version: 1.8.8.

We decided to choose version 1.8.8 for several reasons:
- This version introduced the fix we need for handling comments
- Liferay 70x uses version 1.8.8 for our wrapper module for **org.apache.felix.configadmin**
- **org.apache.felix.fileinstall** switched to using version 1.8.8, specifically to handle comments
  - Reference: https://github.com/apache/felix/commit/ccaab9619150fc36469a9914d42543579e2c6cf6#diff-cd51145cbe0ebcee06e6a274696f5dda
- The latest **org.apache.felix.fileinstall** still uses version 1.8.8
  - Reference: https://github.com/apache/felix/blob/trunk/fileinstall/pom.xml#L56-L58

## Noticeable Changes
Currently, when a **configuration file** with comments is introduced into **osgi/config**, Liferay attempts to store the configuration into the database. The database entry currently includes the commented lines (which is the bug).

With the fix, **configuration files** with comments that are introduced in **osgi/config** will **no longer include** the commented lines when Liferay attempts to store the configuration into the database.

This means that **ANY commented line** introduced into the configuration file will **automatically be erased** (Since Liferay has some kind of mechanism to synchronize the config file and database entry).

----
**ci:test:relevant Results (PASSING):** https://github.com/ericyanLr/liferay-portal/pull/89#issuecomment-435150996

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ericyanLr** [comment]
Hi @rotty3000 ,

I have rebased the fix.
Thanks for reviewing!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7320. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
