### PR TITLE
[TECHNICAL-SUPPORT] LPS-70053

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson @joshuacords @mbowerman @Preston-Crary

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Are there any tests that illustrate the issue? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
We do have a test case   for this. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
We do have a test case  com.liferay.portal.kernel.upgrade.BaseUpgradePortletIdTest for this. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mbowerman** [comment]
@rotty3000 I am not aware of any tests that we use to illustrate performance issues. If you believe there should be a test for this issue, could you please give me an example of another place in the test suite where we test the time it takes to complete a method?

Also, I think you can treat this as a lower priority if you want. I initially marked the LPS as FP5 because we had a client who was urgently waiting for this fix. However, we decided to do an SDH, so I don't think it's very high priority any more.

**Comment by rotty3000** [comment]
Ah.. a performance issue! Ok, as long as the current tests still pass then I'm ok with it. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46152. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
