### PR TITLE
LPS-71877

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/48290. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
