### PR TITLE
Use Http Service standard

### PR DESCRIPTION
**Pull request by csierra**

### CODE REVIEW

**Comment by csierra** [comment]
hey @rotty3000, 

this is what we discussed the other day. Should I open a LPS for this or do we have an already opened LPS for this?

Thx!.

**Comment by csierra** [comment]
ci:stop

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/csierra/liferay-portal/pull/241. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/3a4568c~1...3a4568c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
