### PR TITLE
LPS-65843 el

### PR DESCRIPTION
**Pull request by juangon**
Needed for those bundles using com.sun.el

### CODE REVIEW

**Comment by juangon** [comment]
ci:stop

**Comment by juangon** [comment]
Hi @rotty3000 this PR is important to make Liferay Faces work in Wildfly. Please, if possible, can you review so it can be in GA2? 

thanks!

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:stop

**Comment by juangon** [comment]
Hi @rotty3000 do you have any updates for this issue? It's critical for Wildfly servers and JSF. Thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41009. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
Thanks Ray!

**Pull request closed without merging**
