### PR TITLE
LPS-50757

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Hey Ray, in ConfigAdminPortlet, I see "factoryModel" and "configurationModel"

Are they the same? 

In the *.ftl, I also see "model". Can we make that "curConfigurationModel" if we have a "configurationModel" in the request that it conflicts with.

Also, we have Config and Configuration. For this module, can we stick to one? Either make the package configuration in which all classes are Configuration* or keep the package as config and all classes are Config*

Thx

**Comment by rotty3000** [comment]
>
> Hey Ray, in ConfigAdminPortlet, I see "factoryModel" and
> "configurationModel"
>
> Are they the same?
>

they are not the same.

One is a factory.. the other is an instance.


>  In the *.ftl, I also see "model". Can we make that
> "curConfigurationModel" if we have a "configurationModel" in the request
> that it conflicts with.
>

I'll change it.

Also, we have Config and Configuration. For this module, can we stick to
> one? Either make the package configuration in which all classes are
> Configuration* or keep the package as config and all classes are Config*
>

I'll change the package to configuration.

Shall I change the plugin name as well?

- Ray

**Comment by brianchandotcom** [comment]
Yes, let's change plugin as well

Thx

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23147. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
