### PR TITLE
LPS-54489 - Extract WYSIWYG editors into a module (merged with previous fixes)

### PR DESCRIPTION
**Pull request by peterfellwock**

### CODE REVIEW

**Comment by peterfellwock** [comment]
@mjbradford89 can you look into this failure?

**Comment by mjbradford89** [comment]
@peterfellwock That's the same failure as before.  It looks like the changes I sent you in the gist (https://gist.github.com/mjbradford89/a26478baa4802579ffe3) didn't make it into this pull.  Let me know if you want me to commit it and resend in a pull instead.

**Comment by peterfellwock** [comment]
ci:retest

**Comment by peterfellwock** [comment]
@mjbradford89 submitted fix and retesting

**Comment by mjbradford89** [comment]
ci:retest

**Comment by peterfellwock** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
@peterfellwock can you rebase this please? sorry! :( <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26421. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
