### PR TITLE
LPS-62552 Enable async support in modules

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by stiemannkj1** [comment]
@rotty3000, will this be automatically backported to `7.0.x`?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49769. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/1cc1105031a8~2...1cc1105031a8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49783. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/f156c14003a6~2...f156c14003a6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
