### PR TITLE
LPS-57325

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Ray,

I had sent this to Jorge first: https://github.com/JorgeFerrer/liferay-portal/pull/565
He's not responding and it's for a customer, so could you have a look a this?

Thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28727. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
That was fast... thanks Ray :)

**Pull request closed without merging**
