### PR TITLE
[TECH-SUPPORT] LPS-54730 Images are broken when checking the Use

### PR DESCRIPTION
**Pull request by laszlocsontos**
Hi Ray,

When you create a new item an attach some images to it, upon editing it later on, there is no way to see those images you uploaded.

@zsagia solved it in a way that he displays a link to the stored images. When you click on the click the image can be retried.

Please feel free to give us some feedback if you have some other solution in mind.

Thanks for reviewing!

Cheers,
László

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:retest

**Comment by laszlocsontos** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25937. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
