### PR TITLE
LPS-63695 SCOPE_GROUP root model-resource is missing by default, custom plugins will fail permission checking

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

here I'm fixing the issue that for each group we need separate resource permission records for root model-resource (com.liferay.journal, com.liferay.blogs, ...).

We have 2 kinds of root model-resource scenarios:
1, non-site use - the old way with portlets that are not scoped to site and use `permissionChecker.hasPermission(0, "com.something.model", "com.something.model", "ADD_ASDF")`
2, site related permissions which can modified differently for each site - we use `permissionChecker.hasPermission(groupId, "com.something.site.model", groupId, "ADD_ASDF")`

So for the 2nd type we create (created) individual record per-site (primKey = groupId) so that it can be modified on each site. However, it required developers to programatically create the record which is in fact done by extending `BaseResourcePermissionChecker`. But not everybody knows that, I'd say almost nobody except @juliocamarero and @JorgeFerrer :)

Here I create defaults per-company. I use them when the groupId record is not found so now we don't need to have the per-group records, which in most cases duplicated the defaults only.

This no longer requires developers to extend BaseResourcePermissionChecker, only to declare the root models as `<root>true</root>` in resource-actions.xml, as it should be.

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
Rebased, there was a rebase conflict in ResourceActionsImpl.

**Comment by topolik** [comment]
ci:retest

**Comment by rotty3000** [comment]
Sorry for the delay on this @topolik Is this stiff relevant?

**Comment by topolik** [comment]
Yes, still relevant.

When I saw this might not get into master, I fixed all our portlets and plugins to extend BaseResourcePermissionChecker so we should be safe. But of course this doesn't apply on 3rd party code.

**Comment by rotty3000** [comment]
So you still need this reviewed in other words.... yes?

**Comment by topolik** [comment]
Yes, we need that, priority for 7.0 is now "would-be-nice"

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37905. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/fff99b8~2...fff99b8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
