### PR TITLE
[TECHNICAL-SUPPORT] LPS-69679

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @rotty3000,

Not too sure about this one. Also, let me know if you think someone else should review this. Thanks.

/cc @NolanChan

### CODE REVIEW

**Comment by juangon** [comment]
Hi @NolanChan, I think with this solution will never initialize any WebServlet, WebFilter or WebListener. Is there any problem on user to embed those dependencies?

**Comment by juangon** [comment]
@NolanChan seems isn't clear this is expected behavior, bug link: http://bugs.java.com/view_bug.do?bug_id=7183985

**Comment by NolanChan** [comment]
Hi @juangon I can check again what dependency the customer was lacking (I'm off today but I'll be back in tomorrow). I remember that it was some obscure LDAP dependency that didn't seem necessary for their portlet, which was why I was hesitant to ask them to require it. And as to your comment: 

> I think with this solution will never initialize any WebServlet, WebFilter or WebListener. 

From my understanding of my solution, only classes with unfound annotations will not be initialized. Could you help me understand why no Web components will be loaded?

**Comment by migue** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
@NolanChan ok so if getAnnotations returns the ones with resolved dependencies, then it should work fine. Anyway @migue is working on other fix that would work and seems more conservative.

**Comment by NolanChan** [comment]
Thanks @juangon for letting me know the status of @migue 's work, I think it would be very helpful for me to look at it when it gets released! Is there an LPS that Miguel created?

**Comment by juangon** [comment]
Here is the PR that is supposed to be merged: https://github.com/brianchandotcom/liferay-portal/pull/45834

**Comment by juangon** [comment]
@rotty3000 you can close this PR, it had already been merged into master and 7.0.x

**Pull request closed without merging**
