### PR TITLE
LPS-54098 Fix bookmarks test to work with OSGI

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Ray,

This pull fixes bookmarks test (there weren't running since bookmarks was extracted as an OSGI module and some of them got broken during that time). Actually, in this pull tests are disabled because there's an issue with the CI that prevents us from enable them, but you can manually run the bookmarks test in local to test it if you need it. 

We would like to you to review 2 things here:

1. The new method introduced in the class ResourceBlockPermissionTestUtil.java
2. The commits that revert the ticket LPS-53961 (https://github.com/sergiogonzalez/liferay-portal/commit/f07b20fce02a5166705f764dff01e376b038c5ca https://github.com/sergiogonzalez/liferay-portal/commit/c1837fb0ca364e4b16b6a2eab669059d6b163684 https://github.com/sergiogonzalez/liferay-portal/commit/18b1c40e937524d69bbdc166ffb28fd1336ea426 https://github.com/sergiogonzalez/liferay-portal/commit/74819cd78fcd46b628f4e6a5ee338dd0bd69d5a3). Those commit breaks some test, so we don't know if the logic introduced is wrong or if the tests need to be updated.

I have reopened the LPS-53961 to fix #2.

Thanks!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @robertoDiaz @cgoncas

**Comment by sergiogonzalez** [comment]
Hey @Preston-Crary 

You may need to check this because LPS-53961 breaks some bookmarks test and we have reverted the logic here. 

Thanks

**Comment by Preston-Crary** [comment]
@sergiogonzalez Thanks for the heads up! I'll take a look once this is merged.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25182. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
