### PR TITLE
LPS-73174 | master

### PR DESCRIPTION
**Pull request by holatuwol**
Please see [LPS-73174](https://issues.liferay.com/browse/LPS-73174) for more details.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:reopen

**Comment by holatuwol** [comment]
My pull request added three lines, none of which should have the wrong whitespace.

ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/50078. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
