### PR TITLE
[TECHNICAL-SUPPORT] LPS-59478

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts 

Related to https://github.com/rotty3000/liferay-plugins/pull/68

### CODE REVIEW

**Comment by arbetts** [comment]
@rotty3000 

have you had a chance to review this yet? should i send to someone else?

thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Can you rebase this? It's got merge conflicts on HEAD. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by arbetts** [comment]
will rebase and resend shortly

**Comment by arbetts** [comment]
https://github.com/rotty3000/liferay-portal/pull/1044

**Comment by rotty3000** [comment]
you just needed to push to this branch...

**Comment by arbetts** [comment]
I didn't know it was possible to push to someone else's fork 

arbetts -> jonathanmccann:pull-request-850-LPS-59478

**Comment by rotty3000** [comment]
Just push to the same branch you used originally. It will apply it to the
original PR.

**Comment by arbetts** [comment]
good to know,

Thanks!!

**Pull request closed without merging**
