### PR TITLE
LPS-53996

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @rotty3000,

Attached is an update for http://issues.liferay.com/browse/LPS-53996. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Isn't it likely that countless other timezones might suffer the same problem? Could we make this more generic? <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonmak08** [comment]
I'll let @drewbrokke chime in on this, but this change was in reference to https://github.com/brianchandotcom/liferay-portal/pull/29553#issuecomment-134408321.

**Comment by drewbrokke** [comment]
When tested by moving the system clock in and out of daylight savings time, that was the only timezone that had that issue.  Every other timezone was distinct from the others.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31075. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
