### PR TITLE
LPS-72880 Some ServletRegistrations cannot be obtained via ServletContext.getServletRegistration()

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by juangon** [comment]
@stiemannkj1 sorry Kyle haven't got too much context on these but, do you think that together with Filter and Servlet definitions, Listener definitions should be carried over too?
Thanks!

**Comment by juangon** [comment]
Hmmm seems they are being registered before...so probably don't needed.

**Comment by stiemannkj1** [comment]
@juangon, they are registered [here](https://github.com/stiemannkj1/liferay-portal/blob/f547615b8779b60d5e4591ac78fd42c0620ad517/modules/apps/static/portal-osgi-web/portal-osgi-web-wab-extender/src/main/java/com/liferay/portal/osgi/web/wab/extender/internal/adapter/ModifiableServletContextAdapter.java#L90-L95) right?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/49772. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/13fbcecc8833~1...13fbcecc8833) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
