### PR TITLE
LPS-63181 InlineSQLHelperImpl cannot rely on SCOPE_INDIVIDUAL resource permission

### PR DESCRIPTION
**Pull request by topolik**
Hi Ray,

https://issues.liferay.com/browse/LPS-63181

InlineSQLHelperImpl used following permission check to skip updating the SQL.

```
if (permissionChecker.hasPermission(
	checkGroupId, className, 0, ActionKeys.VIEW)) {

	return sql;
}
```

But after the indiviual resource fix this won't work, there is no entity with primKey==0.

To keep the logic I'm checking resource permissions on higher levels manually.

Thanks.

### CODE REVIEW

**Comment by topolik** [comment]
I need to fix the tests, they call filterFindBy without permission checker.

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
ci:retest

**Comment by topolik** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36178. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
