### PR TITLE
LPS-61088

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @rotty3000

Feels like I am a bit too aggressive?
Should I leave anything outside modules alone?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I think you need to exclude all the bnd files that are not in modules. Those need the classes because they use an old method of building the jar files. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by hhuijser** [comment]
That's what I thought... thanks for the confirmation :)

**Pull request closed without merging**
