### PR TITLE
LPS-73701 Petra messaging

### PR DESCRIPTION
**Pull request by jrao**
LPS-73701 Petra messaging

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/jrao/liferay-portal/pull/29. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/36b9d6a08b5c~1...36b9d6a08b5c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
