### PR TITLE
LPS-80312 Update third-party dependencies to lastest micro versions

### PR DESCRIPTION
**Pull request by jrao**
LPS-80312 Update third-party dependencies to lastest micro versions

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
ci:test

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
Sent https://github.com/shuyangzhou/liferay-portal/pull/6105

**Pull request closed without merging**
