### PR TITLE
[TECHNICAL-SUPPORT] LPS-79311

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian @joshuacords

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
It seems that somehow the Liferay kernel logger crept into the code of this module. Can you please remove it and use the built in logger? If that Logger is not sufficient then please use slf4j API instead. I'm trying to minimize the use of kernel APIs in modules.

**Comment by JaredDomio** [comment]
Updated pr uses the built in logger. [rotty3000#1388](https://github.com/rotty3000/liferay-portal/pull/1388)

**Pull request closed without merging**
