### PR TITLE
[TECHNICAL-SUPPORT] LPS-71194

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @rotty3000,

The issue is that the portal property ```module.framework.web.generator.headers.DynamicImport-Package``` is always used no matter what, even if the WAB has the dependency necessary for the package. This fix scans the WAB's JARs to see what packages are actually necessary. Without this fix, using Spring and Hibernate within a WAB does not work properly.

/cc @holatuwol

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Is there any update on this pull request?

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
I'm going to incorporate this fix into https://github.com/rotty3000/liferay-portal/tree/LPS-70802 (ignore the branch name it's not relevant). But this WIP fixes several issues with the WAB generator. I'm going to role in your changes.

Please note however that I'm currently travelling so it may take a day or two before I can get that done.

**Comment by jonathanmccann** [comment]
That sounds great, thank you for the update.

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
