### PR TITLE
LPS_64981 Gradle cache

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Ray, this is the followup cleanup task for the freemarker taglib issue we discussed.

### CODE REVIEW

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38703. [See changes here.](https://github.com/rotty3000/liferay-portal/compare/1c1ed97~1...1c1ed97) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Guys, the pull was closed automatically... https://github.com/brianchandotcom/liferay-portal/pull/38703

**Comment by rotty3000** [comment]
Strange I never got an email about it. I will forward it again today.

**Comment by jbalsas** [comment]
Oops... thanks for the heads up, Julio! I actually thought it had been
merged since I didn't see it in Brian's queue.

I typed an underscore in the first commit instead of a dash for the lps
number :(

**Pull request closed without merging**
