### PR TITLE
LPS-67378 Fullfill with Servlet 3 spec section 9.4.2, so all javax.servlet.forward.* attributes are 'invoked on the request object passed to the first servlet object in the call chain that received the request from the client'

### PR DESCRIPTION
**Pull request by rotty3000**
@juangon testing here again. Let's see!

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
Hi @rotty3000 did you have a chance to take a look at his?
Thanks!

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
ci:retest

**Comment by rotty3000** [comment]
@juangon, did you see how this causes the portlet TCK to fail some tests?

**Comment by juangon** [comment]
@rotty3000 just read it. This seems to fix a Bridge TCK test, but fails in 8 on portlet TCK. Will investigate what I did wrong...

**Comment by juangon** [comment]
ci:retest

**Comment by rotty3000** [comment]
going to send a new PR to run another test now.

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/rotty3000/liferay-portal/pull/1251. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
see https://github.com/rotty3000/liferay-portal/pull/1251

**Pull request closed without merging**
