### PR TITLE
[TECHNICAL-SUPPORT] LPS-69002

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @NolanChan

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by rotty3000** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
You do realize that this is a backward incompatible change and that you'll need an upgrade process right?

**Comment by NolanChan** [comment]
Hi Rotty, 

From my understanding of the problem, it seems that adding any OSGI portlet with a name that uses a period, hyphen, or space would have never worked to begin with, as [this line](https://github.com/liferay/liferay-portal/blob/7.0.2-ga3/modules/apps/static/portal-osgi-web/portal-osgi-web-portlet-tracker/src/main/java/com/liferay/portal/osgi/web/portlet/tracker/internal/PortletTracker.java#L125-L126) replaces periods with underscores, while spaces and hyphens aren't even touched. This is completely incompatible with getJsSafePortletId.

When the portlet is retrieved, getJsSafePortletId (or [getSafeName](https://github.com/liferay/liferay-portal/blob/7.0.2-ga3/util-java/src/com/liferay/util/JS.java#L85)) destroys all spaces, hyphens, and periods. Therefore, any customer portlet with a name that contains a hyphen/space/period would not work, and only these portlets are affected by the getJsSafePortletId addition.

I believe this is how it works, but please let me know if I'm wrong. Thanks!

**Comment by rotty3000** [comment]
Ok, then if you're confident about it, I trust your judgment.

**Comment by rotty3000** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44870. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
